-- Création de la table motivation
CREATE TABLE motivation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Création de la table todolist
CREATE TABLE todolist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Activer RLS pour les deux tables
ALTER TABLE motivation ENABLE ROW LEVEL SECURITY;
ALTER TABLE todolist ENABLE ROW LEVEL SECURITY;

-- Politiques pour la table motivation
CREATE POLICY "Tout le monde peut voir les motivations"
ON motivation FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Les utilisateurs authentifiés peuvent ajouter des motivations"
ON motivation FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Les utilisateurs authentifiés peuvent supprimer des motivations"
ON motivation FOR DELETE
TO authenticated
USING (true);

-- Politiques pour la table todolist
CREATE POLICY "Tout le monde peut voir les todos"
ON todolist FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Les utilisateurs authentifiés peuvent ajouter des todos"
ON todolist FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Les utilisateurs authentifiés peuvent supprimer des todos"
ON todolist FOR DELETE
TO authenticated
USING (true);

-- Indexes pour améliorer les performances
CREATE INDEX idx_motivation_created_at ON motivation(created_at DESC);
CREATE INDEX idx_todolist_created_at ON todolist(created_at DESC); 